Members:

  - Name: kP_Acc_AHRS
    Description: "Ganho Proporcional para correção da estimativa de Attitude"
    DefaultValue: 25
    Min: 0
    Max: 255

  - Name: kI_Acc_AHRS
    Description: "Ganho Integral para correção da estimativa de Attitude"
    DefaultValue: 50
    Min: 0
    Max: 255

  - Name: kP_Mag_AHRS
    Description: "Ganho Proporcional para correção da estimativa de direção do Yaw"
    DefaultValue: 10
    Min: 0
    Max: 255

  - Name: kI_Mag_AHRS
    Description: "Ganho Integral para correção da estimativa de direção do Yaw"
    DefaultValue: 0
    Min: 0
    Max: 255

  - Name: Angle_Block_Arm
    Description: "Se o Coseno de Z for maior que o valor definido aqui,o sistema não irá armar [Graus]"
    DefaultValue: 25
    Min: 0
    Max: 180

  - Name: AutoLaunch_AHRS_BankAngle
    Description: "Ângulo no AHRS para considerar que o Auto-Launch deve iniciar [Graus]"
    DefaultValue: 45
    Min: 5
    Max: 180

  - Name: AutoLaunch_Velocity_Thresh
    Description: "Velocidade da IMU ou GPS para validar o Auto-Launch [Metros/Segundo]"
    DefaultValue: 3
    Min: 0
    Max: 20

  - Name: AutoLaunch_Motor_Delay
    Description: "Tempo para subir o Throttle em rampa,assim fazendo uma partida suave,isso evita um pico de corrente no ESC [MillisSegundos]"
    DefaultValue: 1500
    Min: 0
    Max: 10000

  - Name: AutoLaunch_Motor_SpinUp_Time
    Description: "Tempo para iniciar o motor após o lançamento for detectado [MillisSegundos]"
    DefaultValue: 500
    Min: 0
    Max: 1000

  - Name: AutoLaunch_Elevator
    Description: "Inclinação no Pitch (Elevator) ao fazer o Auto-Launch [Graus]"
    DefaultValue: 18
    Min: 0
    Max: 100

  - Name: AutoLaunch_MaxThrottle
    Description: "Valor do Throttle aplicado ao motor durante o Auto-Launch [uS]"
    DefaultValue: 1700
    Min: 1000
    Max: 2000

  - Name: AutoLaunch_Exit
    Description: "Cancela o Auto-Launch após o estouro desse tempo [MillisSegundos]"
    DefaultValue: 5000
    Min: 0
    Max: 30000

  - Name: AutoLaunch_Altitude
    Description: "Cancela o Auto-Launch após atingir essa altitude (O tempo acima será ignorado) [Metros]"
    DefaultValue: 0
    Min: 0
    Max: 255

  - Name: AutoLaunch_Sticks_Exit
    Description: "O piloto pode cancelar o Auto-Launch através dos Sticks do rádio somente após o estouro desse tempo [MillisSegundos]"
    DefaultValue: 2000
    Min: 0
    Max: 15000

  - Name: CrashCheck_BankAngle
    Description: "Ângulo da IMU a ser considerado como Crash [Radianos * 100]"
    DefaultValue: 30
    Min: 0
    Max: 255

  - Name: CrashCheck_Timer
    Description: "Estouro de tempo para validar o Crash [Segundos]"
    DefaultValue: 2
    Min: 0
    Max: 255

  - Name: GimbalMinValue
    Description: "Valor minimo do pulso a ser aplicado no Gimbal [uS]"
    DefaultValue: 1000
    Min: 800
    Max: 2200

  - Name: GimbalMaxValue
    Description: "Valor maximo do pulso a ser aplicado no Gimbal [uS]"
    DefaultValue: 2000
    Min: 800
    Max: 2200

  - Name: CrashCheck_BankAngle
    Description: "Valor da aceleração da IMU [Metros/Segundo^2]"
    DefaultValue: 3
    Min: 0
    Max: 20

  - Name: ThrottleMixGain
    Description: "Valor de ganho do Throttle para o mixer do PID"
    DefaultValue: 1.0
    Min: 0
    Max: 1

  - Name: AutoDisarm_Time
    Description: "Estouro de tempo para desarmar a controladora em nivel baixo de Throttle [Segundos]"
    DefaultValue: 5
    Min: 0
    Max: 255

  - Name: AutoDisarm_Throttle_Min
    Description: "Valor maximo do Throttle tolerado para iniciar a contagem do Auto-Desarmamento [uS]"
    DefaultValue: 1100
    Min: 800
    Max: 1500

  - Name: AutoDisarm_YPR_Min
    Description: "Valor minimo tolerado nos canais Yaw,Pitch e Roll para validar o Auto-Desarmamento [uS]"
    DefaultValue: 1450
    Min: 800
    Max: 1500

  - Name: AutoDisarm_YPR_Max
    Description: "Valor maximo tolerado nos canais Yaw,Pitch e Roll para validar o Auto-Desarmamento [uS]"
    DefaultValue: 1550
    Min: 800
    Max: 2200

  - Name: GPS_Baud_Rate
    Description: "0 - 9600KBPS / 1 - 19200KBPS / 2 - 38400KBPS / 3 - 57600KBPS / 4 - 115200KBPS"
    DefaultValue: 4
    Min: 0
    Max: 4

  - Name: Navigation_Vel
    Description: "Velocidade maxima de navegação em modos de voo que utilizam o GPS [Centimetos/Segundo]"
    DefaultValue: 400
    Min: 0
    Max: 400

  - Name: GPS_WP_Radius
    Description: "Raio do ponto para validar que o mesmo foi alcançado em modo WayPoint e RTH [Metros]"
    DefaultValue: 2
    Min: 0
    Max: 255

  - Name: GPS_RTH_Land_Radius
    Description: "Em modo RTH,inicia o Land se o UAV estiver dentro do tamanho desse raio definido aqui,caso contrario,o UAV irá subir até a altitude definido em 'RTH Altitude' nas configurações basicas,voltar ao Home-Point,e fazer o Land [Metros]"
    DefaultValue: 10
    Min: 0
    Max: 255

  - Name: GPS_TiltCompensation
    Description: "Valor para compensar o rate de navegação em modo WayPoint e RTH (Multirotores apenas)"
    DefaultValue: 20
    Min: 0
    Max: 100

  - Name: AirSpeed_Samples
    Description: "Número de amostras para calibrar o Tubo de Pitot"
    DefaultValue: 15
    Min: 0
    Max: 255

  - Name: Arm_Time_Safety
    Description: "Tempo seguro para armar com os sticks em posição de armamento [Segundos]"
    DefaultValue: 2
    Min: 0
    Max: 255

  - Name: Disarm_Time_Safety
    Description: "Tempo seguro para desarmar com os sticks em posição de desarmamento [Segundos]"
    DefaultValue: 2
    Min: 0
    Max: 255

  - Name: Compass_Cal_Timer
    Description: "Tempo maximo de calibração do Compass [Segundos]"
    DefaultValue: 60
    Min: 0
    Max: 120

  - Name: Cont_Servo_Trim_Rot_Limit
    Description: "Os pontos médios dos servos serão atualizados sempre que a rotação total do UAV for menor que esse limite [Graus/s]"
    DefaultValue: 15
    Min: 1
    Max: 60